### ISSUE TITLE
Connecting to TTN

### ISSUE THREAD

**Issue by StevenCellist** [lora-gateway/esxp1302#24]
Hi folks, I just got my concentrator card in the mail as well as the miniPCIe break-out a few days earlier (perfect & fast shipping!). If I understand correctly however, it is not possible yet to connect the ESXP1302 to TTN or other 'online' (non-local) network servers. Is that right, and if so, where should I look to try and see if I can get it running? Cheers!

**Comment by danielkucera** [comment]
Hi, of course it is.
You just need to set you NS accordingly.
![IMG_20240629_071605](https://github.com/lora-gateway/esxp1302/assets/1734256/ecb3b60e-dfd7-4772-b1d0-ccb30e0563d2)

**Comment by StevenCellist** [comment]
Ah, according to the [user guide](https://github.com/lora-gateway/esxp1302/blob/main/doc/user_guide.md#configuration-by-web-ui), it says that domain names don't work and IP addresses should be used.
And as far as I'm used to, I thought I'd need to set the API key for the gateway to function correctly.. how does that work here?

**Comment by danielkucera** [comment]
That might be some old information, right @dennis4lora ?
Api key is only needed for the new protocol. Legacy packet forwarder works without. I don't remember exactly now if something had to be set in TTN console but I think no.

**Comment by StevenCellist** [comment]
Do you have your ESXP connected to TTN? It sounds impossible to me that you can have it working without API key, because any and all packet forwarder gateways I've used including legacy ones require the API key.

**Comment by danielkucera** [comment]
Yes, I do.

**Comment by StevenCellist** [comment]
Apparently, the statistics on their own do not trigger TTN to show the gateway. Having resolved the I2C wiring means messages now come through and the gateway functions nicely. Definitely interesting there's no key required, but that's probably why it's called legacy ;)
Thank you!

**Comment by danielkucera** [comment]
Nice, YW.

**Comment by chunis** [comment]
> Ah, according to the [user guide](https://github.com/lora-gateway/esxp1302/blob/main/doc/user_guide.md#configuration-by-web-ui), it says that domain names don't work and IP addresses should be used.

That information is outdated now and needs to be corrected. Thanks for point it out. :-)

@danielkucera, @StevenCellist :

In fact, there are two kinds of gateway protocol both supported by Semtech:
- UDP based packet-forwarder (https://github.com/lora-net/sx1302_hal) (let's call it PF).
- Basics Station (https://github.com/lorabasics/basicstation) (let's call it BS).

The reason why there are 2 instead of 1, is because BS is designed by another company named TrackNet before it was acquired by Semtech. PF is older and simpler while BS has some advanced features but more complex. For example, it requires API key for `CUPS` (https://www.thethingsindustries.com/docs/gateways/concepts/lora-basics-station/cups/).

TTN provides some information for both:
- https://www.thethingsindustries.com/docs/gateways/concepts/udp/
- https://www.thethingsindustries.com/docs/gateways/concepts/lora-basics-station/

Final word: **ESXP1302 derives from PF**. That's why it doesn't require API key.
