### ISSUE TITLE
LORAWAN support?

### ISSUE THREAD

**Issue by michcfr** [lora-gateway/esxp1302#9]
Hello,
Do you plan to support also LORAWAN in the future?
Thank you
Michel

**Comment by danielkucera** [comment]
This is LoRaWAN.

**Comment by dennis4lora** [comment]
Let me give a little more clarification here.

LoRaWAN protocol mainly includes 2 parts: the core protocol and the Region parameters. LoRaWAN is a protocol mostly defined for the Node and the Network Server, that's why sometimes it's important to know the version of node and the NS, and if the versions are not match, there could be compatibility issues.

On the other side, the function of gateways are just **forward packets**, that's why the application is named  `packet-forwarder`. Gateways just transfer packets between nodes and NS, it doesn't care the LoRaWAN protocol much, instead it has its own Protocol defined [here](https://github.com/Lora-net/sx1302_hal/blob/master/packet_forwarder/PROTOCOL.md).

The frequency settings of gateway need to follow the LoRaWAN region parameters for the whole LoRa network to work. So far esxp1302 supports EU868/US915/CN470, but we plan to have full support for all region parameters in the near future.
